"""add follow up table

Revision ID: 0b8e7e655ca5
Revises: bd559109dc4b
Create Date: 2024-04-20 12:56:27.611045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8e7e655ca5'
down_revision: Union[str, None] = 'bd559109dc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_media', sa.Column('followup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_media', 'follow_up', ['followup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_media', type_='foreignkey')
    op.drop_column('lead_media', 'followup_id')
    # ### end Alembic commands ###
