"""add country_code in lead

Revision ID: 165ee015ab2c
Revises: 6aef4276c8fa
Create Date: 2024-04-17 17:53:06.917261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '165ee015ab2c'
down_revision: Union[str, None] = '6aef4276c8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsappcontent', 'content',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsappcontent', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
