"""add remark in lead

Revision ID: 21453102ea9d
Revises: b89eae76ad96
Create Date: 2024-04-16 15:23:57.922231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21453102ea9d'
down_revision: Union[str, None] = 'b89eae76ad96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('lead', sa.Column('remarks', sa.Text(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('lead', 'remarks')
    # ### end Alembic commands ###
