"""your_revision_message

Revision ID: 26d446ea8e7b
Revises: a589cab76a78
Create Date: 2024-02-23 16:28:30.020281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d446ea8e7b'
down_revision: Union[str, None] = 'a589cab76a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('approximate_amount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'approximate_amount')
    # ### end Alembic commands ###
