"""is_followup in lead

Revision ID: 387aa936fc6a
Revises: 1ac102300dff
Create Date: 2024-04-20 17:13:00.827795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '387aa936fc6a'
down_revision: Union[str, None] = '1ac102300dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'is_followup',
               existing_type=mysql.TINYINT(),
               comment='1->active,2-completed,-1->inactive',
               existing_comment='1->active,-1->inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead', 'is_followup',
               existing_type=mysql.TINYINT(),
               comment='1->active,-1->inactive',
               existing_comment='1->active,2-completed,-1->inactive',
               existing_nullable=True)
    # ### end Alembic commands ###
