"""add follow up table

Revision ID: 48145d79d967
Revises: d315fdd63e52
Create Date: 2024-04-20 09:54:41.639241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48145d79d967'
down_revision: Union[str, None] = 'd315fdd63e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_up', 'followup_status',
               existing_type=mysql.TINYINT(),
               comment=' 1->follow_up,2-completed,-1->cancelled',
               existing_comment=' 1->follow_up,2-completeed-1->cancelled',
               existing_nullable=True)
    op.drop_constraint('follow_up_ibfk_3', 'follow_up', type_='foreignkey')
    op.drop_column('follow_up', 'lead_status_id')
    op.drop_column('follow_up', 'leadStatus')
    op.add_column('lead_history', sa.Column('followup_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead_history', 'follow_up', ['followup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_history', type_='foreignkey')
    op.drop_column('lead_history', 'followup_id')
    op.add_column('follow_up', sa.Column('leadStatus', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('follow_up', sa.Column('lead_status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('follow_up_ibfk_3', 'follow_up', 'lead_status', ['lead_status_id'], ['id'])
    op.alter_column('follow_up', 'followup_status',
               existing_type=mysql.TINYINT(),
               comment=' 1->follow_up,2-completeed-1->cancelled',
               existing_comment=' 1->follow_up,2-completed,-1->cancelled',
               existing_nullable=True)
    # ### end Alembic commands ###
