"""add user,owner,station tables

Revision ID: 487d6e0ede97
Revises: c79b86f118db
Create Date: 2024-06-11 10:22:30.088439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487d6e0ede97'
down_revision: Union[str, None] = 'c79b86f118db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('deletedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead', 'user', ['deletedBy'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead', type_='foreignkey')
    op.drop_column('lead', 'deletedBy')
    # ### end Alembic commands ###
