"""add category_type table

Revision ID: 497395810e7c
Revises: 066a74fccbbf
Create Date: 2024-05-08 14:34:31.493105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497395810e7c'
down_revision: Union[str, None] = '066a74fccbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('demo_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'demo_date')
    # ### end Alembic commands ###
