"""add category_type table

Revision ID: 603ce3942255
Revises: c8b2029eaddc
Create Date: 2024-05-10 09:27:46.355174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ce3942255'
down_revision: Union[str, None] = 'c8b2029eaddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_up', sa.Column('enquiry_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'follow_up', 'enquiry_type', ['enquiry_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follow_up', type_='foreignkey')
    op.drop_column('follow_up', 'enquiry_type_id')
    # ### end Alembic commands ###
