"""intial commit

Revision ID: 67ac0f47da18
Revises: 
Create Date: 2024-06-25 09:44:13.804449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67ac0f47da18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mobile_no_length', sa.String(length=50), nullable=True),
    sa.Column('iso', sa.CHAR(length=2), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('sms_enabled', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_country_code', sa.String(length=10), nullable=True),
    sa.Column('whatsapp_country_code', sa.String(length=10), nullable=True),
    sa.Column('alter_country_code', sa.String(length=10), nullable=True),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment='1->superAdmin,2->Admin,2->Dealer,4->Employee,5->customer'),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('alternative_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_no', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('states', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('reset_key', sa.String(length=255), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('otp_expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsappcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('renewed_at', sa.DateTime(), nullable=True),
    sa.Column('device_type', mysql.TINYINT(display_width=1), nullable=True, comment='1-Android, 2-iOS'),
    sa.Column('validity', mysql.TINYINT(display_width=1), nullable=True, comment='0-Expired, 1- Lifetime'),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('push_device_id', sa.String(length=255), nullable=True),
    sa.Column('device_ip', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_followup', mysql.TINYINT(), nullable=True, comment='1->active,2-completed,-1->inactive'),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('contact_person', sa.String(length=250), nullable=True),
    sa.Column('lead_code', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternative_no', sa.String(length=20), nullable=True),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('customer_category_id', sa.Integer(), nullable=True),
    sa.Column('enquiry_type_id', sa.Integer(), nullable=True),
    sa.Column('lead_status_id', sa.Integer(), nullable=True),
    sa.Column('requirements_id', sa.String(length=255), nullable=True),
    sa.Column('refer_country_code', sa.String(length=10), nullable=True),
    sa.Column('approximate_amount', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('states', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('deletedBy', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_valid', mysql.TINYINT(), nullable=True, comment='1->valid,2->invalid'),
    sa.Column('refered_by', sa.String(length=200), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('comments_description', sa.Text(), nullable=True),
    sa.Column('created_t', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted,0->inactive'),
    sa.Column('is_transferred', mysql.TINYINT(), nullable=True, comment='1->yes,0->No'),
    sa.Column('competitor_name', sa.String(length=250), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('tempComment', sa.Text(), nullable=True),
    sa.Column('schedule_date', sa.DateTime(), nullable=True),
    sa.Column('poc_date', sa.DateTime(), nullable=True),
    sa.Column('demo_date', sa.DateTime(), nullable=True),
    sa.Column('transferComment', sa.Text(), nullable=True),
    sa.Column('refered_ph_no', sa.String(length=20), nullable=True),
    sa.Column('drop_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_category_id'], ['customer_category.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deletedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enquiry_type_id'], ['enquiry_type.id'], ),
    sa.ForeignKeyConstraint(['lead_status_id'], ['lead_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('file_type', mysql.TINYINT(), nullable=True, comment='1-video,2-photo'),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('enquiry_type_id', sa.Integer(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('followup_dt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('followup_status', mysql.TINYINT(), nullable=True, comment=' 1->follow_up,2-completed,-1->cancelled'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment=' 1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['createdBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enquiry_type_id'], ['enquiry_type.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('followup_id', sa.Integer(), nullable=True),
    sa.Column('leadStatus', sa.String(length=200), nullable=True),
    sa.Column('lead_status_id', sa.Integer(), nullable=True),
    sa.Column('enquiry_type_id', sa.Integer(), nullable=True),
    sa.Column('changedBy', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment=' 1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['changedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enquiry_type_id'], ['enquiry_type.id'], ),
    sa.ForeignKeyConstraint(['followup_id'], ['follow_up.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['lead_status_id'], ['lead_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('followup_id', sa.Integer(), nullable=True),
    sa.Column('lead_history_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('upload_by', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['followup_id'], ['follow_up.id'], ),
    sa.ForeignKeyConstraint(['lead_history_id'], ['lead_history.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['upload_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_media')
    op.drop_table('lead_history')
    op.drop_table('follow_up')
    op.drop_table('media')
    op.drop_table('lead')
    op.drop_table('requirements')
    op.drop_table('lead_status')
    op.drop_table('enquiry_type')
    op.drop_table('customer_category')
    op.drop_table('competitors')
    op.drop_table('api_tokens')
    op.drop_table('whatsappcontent')
    op.drop_table('user')
    op.drop_table('industry')
    op.drop_table('country')
    # ### end Alembic commands ###
