"""add country_code in lead

Revision ID: 6aef4276c8fa
Revises: 1b9e960e5f6e
Create Date: 2024-04-17 14:19:56.543996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6aef4276c8fa'
down_revision: Union[str, None] = '1b9e960e5f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_country_code', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('whatsapp_country_code', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('alter_country_code', sa.String(length=10), nullable=True))
    op.drop_column('user', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country_code', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('user', 'alter_country_code')
    op.drop_column('user', 'whatsapp_country_code')
    op.drop_column('user', 'phone_country_code')
    # ### end Alembic commands ###
