"""add country_code in lead

Revision ID: 73c6dadc5084
Revises: 165ee015ab2c
Create Date: 2024-04-18 11:21:26.081775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c6dadc5084'
down_revision: Union[str, None] = '165ee015ab2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('refer_country_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'refer_country_code')
    # ### end Alembic commands ###
