"""your_revision_message

Revision ID: 89e0acdd9c7f
Revises: f0b33f5fa496
Create Date: 2024-02-23 16:30:35.832488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e0acdd9c7f'
down_revision: Union[str, None] = 'f0b33f5fa496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lead_media_ibfk_1', 'lead_media', type_='foreignkey')
    op.create_foreign_key(None, 'lead_media', 'lead', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_media', type_='foreignkey')
    op.create_foreign_key('lead_media_ibfk_1', 'lead_media', 'requirements', ['lead_id'], ['id'])
    # ### end Alembic commands ###
