"""your_revision_message

Revision ID: a589cab76a78
Revises: 2594cb48e5cd
Create Date: 2024-02-23 12:37:07.778398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a589cab76a78'
down_revision: Union[str, None] = '2594cb48e5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('leadStatus', sa.String(length=200), nullable=True),
    sa.Column('lead_status_id', sa.Integer(), nullable=True),
    sa.Column('changedBy', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment=' 1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['changedBy'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['lead_status_id'], ['lead_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_history')
    # ### end Alembic commands ###
