"""add category_type table

Revision ID: b1e78c3f06b7
Revises: 603ce3942255
Create Date: 2024-05-10 10:53:14.598984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e78c3f06b7'
down_revision: Union[str, None] = '603ce3942255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lead', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead', type_='foreignkey')
    op.drop_column('lead', 'created_by')
    # ### end Alembic commands ###
