"""your_revision_message

Revision ID: b89eae76ad96
Revises: e147b051163e
Create Date: 2024-02-24 14:57:33.694888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b89eae76ad96'
down_revision: Union[str, None] = 'e147b051163e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_media', 'file_type')
    op.add_column('user', sa.Column('dealer_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['dealer_id'], ['id'])
    op.drop_column('user', 'delar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('delar_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'user', ['delar_id'], ['id'])
    op.drop_column('user', 'dealer_id')
    op.add_column('lead_media', sa.Column('file_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-video,2-photo'))
    # ### end Alembic commands ###
