"""add country_code in lead

Revision ID: c3059a53ebd2
Revises: fd408107ddfc
Create Date: 2024-04-16 17:43:12.068833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3059a53ebd2'
down_revision: Union[str, None] = 'fd408107ddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsappcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=10), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsappcontent')
    # ### end Alembic commands ###
