"""add user,owner,station tables

Revision ID: c79b86f118db
Revises: b1e78c3f06b7
Create Date: 2024-06-11 10:06:40.200754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c79b86f118db'
down_revision: Union[str, None] = 'b1e78c3f06b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    # op.add_column('lead', sa.Column('deletedBy', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'lead', 'user', ['deletedBy'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'lead', type_='foreignkey')
    pass
    # op.drop_column('lead', 'deletedBy')
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    # sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    # sa.Column('job_state', sa.BLOB(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
