"""your_revision_message

Revision ID: f0b33f5fa496
Revises: c00ef76d0aa6
Create Date: 2024-02-23 16:29:59.009445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0b33f5fa496'
down_revision: Union[str, None] = 'c00ef76d0aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('file_type', mysql.TINYINT(), nullable=True, comment='1-video,2-photo'),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['lead_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lead_madia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_madia',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('file_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-video,2-photo'),
    sa.Column('lead_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.ForeignKeyConstraint(['lead_id'], ['requirements.id'], name='lead_madia_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('lead_media')
    # ### end Alembic commands ###
