"""add country_code in lead

Revision ID: fd408107ddfc
Revises: 21453102ea9d
Create Date: 2024-04-16 17:33:32.341337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd408107ddfc'
down_revision: Union[str, None] = '21453102ea9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('image', sa.String(length=255), nullable=True))
    op.alter_column('country', 'country_code',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='phone code',
               existing_nullable=True)
    op.alter_column('country', 'sms_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='1->active,-1->deleted',
               existing_server_default=sa.text("'0'"))
    op.alter_column('country', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='1->active,-1->deleted',
               existing_comment='0->Inactive, 1->Active',
               existing_server_default=sa.text("'1'"))
    op.drop_table_comment(
        'country',
        existing_comment='Country master table',
        schema=None
    )
    op.drop_column('country', 'img')
    op.drop_column('country', 'mobile_no_length')
    op.add_column('lead', sa.Column('country_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'country_code')
    op.add_column('country', sa.Column('mobile_no_length', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('country', sa.Column('img', mysql.VARCHAR(length=255), nullable=True, comment='flag images or any icon images'))
    op.create_table_comment(
        'country',
        'Country master table',
        existing_comment=None,
        schema=None
    )
    op.alter_column('country', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='0->Inactive, 1->Active',
               existing_comment='1->active,-1->deleted',
               existing_server_default=sa.text("'1'"))
    op.alter_column('country', 'sms_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='1->active,-1->deleted',
               existing_server_default=sa.text("'0'"))
    op.alter_column('country', 'country_code',
               existing_type=mysql.VARCHAR(length=10),
               comment='phone code',
               existing_nullable=True)
    op.drop_column('country', 'image')
    # ### end Alembic commands ###
